# Generated by Django 3.2.6 on 2022-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.TextField(default='Tufts University'),
        ),
    ]
